### ISSUE TITLE
Equal metrics around caps

### ISSUE THREAD

**Issue by LosDragonflyos** [kaspernordkvist/uncut_sans#5]
Roman Shamin explained this issue better than I ever could and it enables both graphic and web designers to center text properly without manual adjustments; worth considering. Thanks!

https://threadreaderapp.com/thread/1562801657691672576.html

https://threadreaderapp.com/thread/1546920413908942852.html

**Comment by kaspernordkvist** [comment]
Hey! This should already be the case

![bb@2x](https://github.com/kaspernordkvist/uncut_sans/assets/998601/b2bf5f47-e6de-45fe-bd91-4995dd3791ab)
